In [1]:
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.grid_search import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
import scipy.stats as scipy
from sklearn.ensemble import RandomForestClassifier 
from sklearn import preprocessing
from sklearn import metrics


train = r"C:\Users\Krishna Teja\Desktop\bigdata\train.csv"
test =  r"C:\Users\Krishna Teja\Desktop\bigdata\test.csv"

train = pd.read_csv(train)
test = pd.read_csv(test)

In [3]:
import matplotlib.pyplot as plt
train['Elevation'].plot()
plt.show()
train.describe()

Elevation        Aspect         Slope  \
count  15120.000000  15120.000000  15120.000000   
mean    2749.322553    156.676653     16.501587   
std      417.678187    110.085801      8.453927   
min     1863.000000      0.000000      0.000000   
25%     2376.000000     65.000000     10.000000   
50%     2752.000000    126.000000     15.000000   
75%     3104.000000    261.000000     22.000000   
max     3849.000000    360.000000     52.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                      15120.000000                    15120.000000   
mean                         227.195701                       51.076521   
std                          210.075296                       61.239406   
min                            0.000000                     -146.000000   
25%                           67.000000                        5.000000   
50%                          180.000000                       32.000000   
75%                          330.000000                       79.000000   
max                         1343.000000                      554.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                     15120.000000   15120.000000    15120.000000   
mean                       1714.023214     212.704299      218.965608   
std                        1325.066358      30.561287       22.801966   
min                           0.000000       0.000000       99.000000   
25%                         764.000000     196.000000      207.000000   
50%                        1316.000000     220.000000      223.000000   
75%                        2270.000000     235.000000      235.000000   
max                        6890.000000     254.000000      254.000000   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points      ...       \
count   15120.000000                        15120.000000      ...        
mean      135.091997                         1511.147288      ...        
std        45.895189                         1099.936493      ...        
min         0.000000                            0.000000      ...        
25%       106.000000                          730.000000      ...        
50%       138.000000                         1256.000000      ...        
75%       167.000000                         1988.250000      ...        
max       248.000000                         6993.000000      ...        

        Soil_Type32   Soil_Type33   Soil_Type34   Soil_Type35   Soil_Type36  \
count  15120.000000  15120.000000  15120.000000  15120.000000  15120.000000   
mean       0.045635      0.040741      0.001455      0.006746      0.000661   
std        0.208699      0.197696      0.038118      0.081859      0.025710   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

        Soil_Type37   Soil_Type38   Soil_Type39   Soil_Type40    Cover_Type  
count  15120.000000  15120.000000  15120.000000  15120.000000  15120.000000  
mean       0.002249      0.048148      0.043452      0.030357      4.000000  
std        0.047368      0.214086      0.203880      0.171574      2.000066  
min        0.000000      0.000000      0.000000      0.000000      1.000000  
25%        0.000000      0.000000      0.000000      0.000000      2.000000  
50%        0.000000      0.000000      0.000000      0.000000      4.000000  
75%        0.000000      0.000000      0.000000      0.000000      6.000000  
max        1.000000      1.000000      1.000000      1.000000      7.000000  

[8 rows x 55 columns]

In [3]:
train.Elevation.value_counts()

2290    25
2830    25
3371    24
3244    23
2820    23
2955    23
2795    23
2952    23
2962    22
2304    22
2809    22
2978    22
2413    22
2707    22
2850    22
2763    22
2289    21
2739    21
2827    21
2784    21
2807    21
2328    21
2311    20
3256    20
2751    20
2336    20
2340    20
2317    20
2264    20
3400    20
        ..
3529     1
3537     1
3722     1
3495     1
3491     1
3721     1
1932     1
3559     1
3753     1
3761     1
3591     1
3475     1
3499     1
3836     1
1997     1
3844     1
1901     1
1925     1
1965     1
1973     1
1989     1
3731     1
3523     1
3675     1
3643     1
3635     1
3603     1
3555     1
3497     1
3737     1
Name: Elevation, dtype: int64

In [6]:
train.describe()

Id     Elevation        Aspect         Slope  \
count  15120.00000  15120.000000  15120.000000  15120.000000   
mean    7560.50000   2749.322553    156.676653     16.501587   
std     4364.91237    417.678187    110.085801      8.453927   
min        1.00000   1863.000000      0.000000      0.000000   
25%     3780.75000   2376.000000     65.000000     10.000000   
50%     7560.50000   2752.000000    126.000000     15.000000   
75%    11340.25000   3104.000000    261.000000     22.000000   
max    15120.00000   3849.000000    360.000000     52.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                      15120.000000                    15120.000000   
mean                         227.195701                       51.076521   
std                          210.075296                       61.239406   
min                            0.000000                     -146.000000   
25%                           67.000000                        5.000000   
50%                          180.000000                       32.000000   
75%                          330.000000                       79.000000   
max                         1343.000000                      554.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                     15120.000000   15120.000000    15120.000000   
mean                       1714.023214     212.704299      218.965608   
std                        1325.066358      30.561287       22.801966   
min                           0.000000       0.000000       99.000000   
25%                         764.000000     196.000000      207.000000   
50%                        1316.000000     220.000000      223.000000   
75%                        2270.000000     235.000000      235.000000   
max                        6890.000000     254.000000      254.000000   

       Hillshade_3pm      ...        Soil_Type30   Soil_Type31   Soil_Type32  \
count   15120.000000      ...       15120.000000  15120.000000  15120.000000   
mean      135.091997      ...           0.047950      0.021958      0.045635   
std        45.895189      ...           0.213667      0.146550      0.208699   
min         0.000000      ...           0.000000      0.000000      0.000000   
25%       106.000000      ...           0.000000      0.000000      0.000000   
50%       138.000000      ...           0.000000      0.000000      0.000000   
75%       167.000000      ...           0.000000      0.000000      0.000000   
max       248.000000      ...           1.000000      1.000000      1.000000   

        Soil_Type33   Soil_Type35   Soil_Type37   Soil_Type38   Soil_Type39  \
count  15120.000000  15120.000000  15120.000000  15120.000000  15120.000000   
mean       0.040741      0.006746      0.002249      0.048148      0.043452   
std        0.197696      0.081859      0.047368      0.214086      0.203880   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

        Soil_Type40    Cover_Type  
count  15120.000000  15120.000000  
mean       0.030357      4.000000  
std        0.171574      2.000066  
min        0.000000      1.000000  
25%        0.000000      2.000000  
50%        0.000000      4.000000  
75%        0.000000      6.000000  
max        1.000000      7.000000  

[8 rows x 47 columns]

In [15]:
c =train.Elevation.unique()
print c.size


1665


In [17]:
train.Vertical_Distance_To_Hydrology.value_counts()

 0      1890
 5       217
 3       206
 4       200
 8       198
 7       182
 10      176
 9       166
 2       165
 6       162
 11      159
 12      159
 13      158
 22      140
 14      140
 1       139
 20      135
 23      133
 16      132
 17      126
 19      126
 21      125
-1       123
 25      122
 18      121
 15      120
-2       120
 37      114
 29      114
 26      114
        ... 
-95        1
-103       1
 249       1
 289       1
 305       1
 321       1
 345       1
 369       1
 393       1
 401       1
-54        1
-110       1
-134       1
 258       1
 266       1
 274       1
 282       1
 330       1
 338       1
 346       1
 554       1
-61        1
-69        1
-85        1
 291       1
 299       1
 315       1
 387       1
 327       1
 395       1
Name: Vertical_Distance_To_Hydrology, dtype: int64

In [18]:
d=train.Vertical_Distance_To_Hydrology.unique()
print d.size


423


In [83]:
def elevation_tr(row):
    if row['Elevation'] >= 1800 and row['Elevation'] < 1900:
        return '1800s'
    elif row['Elevation'] >= 1900 and row['Elevation'] < 2000:
        return '1900s'
    elif row['Elevation'] >= 2000 and row['Elevation'] < 2100:
        return '2000s'
    elif row['Elevation'] >= 2100 and row['Elevation'] < 2200:
        return '2100s'
    elif row['Elevation'] >= 2200 and row['Elevation'] < 2300:
        return '2200s'
    elif row['Elevation'] >= 2300 and row['Elevation'] < 2400:
        return '2300s'
    elif row['Elevation'] >= 2400 and row['Elevation'] < 2500:
        return '2400s'
    elif row['Elevation'] >= 2500 and row['Elevation'] < 2600:
        return '2500s'
    elif row['Elevation'] >= 2600 and row['Elevation'] < 2700:
        return '2600s'
    elif row['Elevation'] >= 2700 and row['Elevation'] < 2800:
        return '2700s'
    elif row['Elevation'] >= 2800 and row['Elevation'] < 2900:
        return '2800s'
    elif row['Elevation'] >= 2900 and row['Elevation'] < 3000:
        return '2900s'
    elif row['Elevation'] >= 3000 and row['Elevation'] < 3100:
        return '3000s'
    elif row['Elevation'] >= 3100 and row['Elevation'] < 3200:
        return '3100s'
    elif row['Elevation'] >= 3200 and row['Elevation'] < 3300:
        return '3200s'
    elif row['Elevation'] >= 3300 and row['Elevation'] < 3400:
        return '3300s'
    elif row['Elevation'] >= 3400 and row['Elevation'] < 3500:
        return '3400s'
    elif row['Elevation'] >= 3500 and row['Elevation'] < 3600:
        return '3500s'
    elif row['Elevation'] >= 3600 and row['Elevation'] < 3700:
        return '3600s'
    elif row['Elevation'] >= 3700 and row['Elevation'] < 3800:
        return '3700s'
    elif row['Elevation'] >= 3800 and row['Elevation'] < 3900:
        return '3800s'
    
    else:
        return 'unknown'
    
train['Elevation'] = train.apply(lambda row: elevation_tr(row), axis=1)
#test['Elevation'] = test.apply(lambda row: elevation_tr(row), axis=1)

In [79]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 55 columns):
Elevation                             15120 non-null object
Aspect                                15120 non-null int64
Slope                                 15120 non-null int64
Horizontal_Distance_To_Hydrology      15120 non-null int64
Vertical_Distance_To_Hydrology        15120 non-null int64
Horizontal_Distance_To_Roadways       15120 non-null int64
Hillshade_9am                         15120 non-null int64
Hillshade_Noon                        15120 non-null int64
Hillshade_3pm                         15120 non-null int64
Horizontal_Distance_To_Fire_Points    15120 non-null int64
Wilderness_Area1                      15120 non-null int64
Wilderness_Area2                      15120 non-null int64
Wilderness_Area3                      15120 non-null int64
Wilderness_Area4                      15120 non-null int64
Soil_Type1                            15120 non-null int64
Soil_

In [37]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=250,learning_rate=1.0).fit(train1,train2)
predicted_classification = clf.predict(test1)
print(accuracy_score(test2, predicted_classification))

0.719907407407


In [40]:
c =train.Horizontal_Distance_To_Hydrology.unique()
print c.size


400


In [84]:
def horizontal_tr(row):
    if row['Horizontal_Distance_To_Hydrology'] >= 0 and row['Horizontal_Distance_To_Hydrology'] < 100:
        return '0s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 100 and row['Horizontal_Distance_To_Hydrology'] < 200:
        return '100s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 200 and row['Horizontal_Distance_To_Hydrology'] < 300:
        return '200s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 300 and row['Horizontal_Distance_To_Hydrology'] < 400:
        return '300s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 400 and row['Horizontal_Distance_To_Hydrology'] < 500:
        return '400s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 500 and row['Horizontal_Distance_To_Hydrology'] < 600:
        return '500s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 600 and row['Horizontal_Distance_To_Hydrology'] < 700:
        return '600s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 700 and row['Horizontal_Distance_To_Hydrology'] < 800:
        return '700s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 800 and row['Horizontal_Distance_To_Hydrology'] < 900:
        return '800s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 900 and row['Horizontal_Distance_To_Hydrology'] < 1000:
        return '900s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 1000 and row['Horizontal_Distance_To_Hydrology'] < 1100:
        return '1000s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 1100 and row['Horizontal_Distance_To_Hydrology'] < 1200:
        return '1100s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 100 and row['Horizontal_Distance_To_Hydrology'] < 200:
        return '1200s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 100 and row['Horizontal_Distance_To_Hydrology'] < 200:
        return '1300s'
    elif row['Horizontal_Distance_To_Hydrology'] >= 100 and row['Horizontal_Distance_To_Hydrology'] < 200:
        return '1400s'
    
    else:
        return 'unknown'
    
train['Horizontal_Distance_To_Hydrology'] = train.apply(lambda row: horizontal_tr(row), axis=1)
#test['Horizontal_Distance_To_Hydrology'] = test.apply(lambda row: horizontal_tr(row), axis=1)

In [42]:
train.Horizontal_Distance_To_Roadways.value_counts()

150     88
120     56
390     47
618     45
1110    43
700     41
108     38
1273    37
900     37
212     37
335     37
990     37
242     36
607     36
361     35
1082    35
228     34
750     34
277     34
450     34
1050    34
1020    34
960     33
1167    33
1140    33
360     32
180     32
484     31
210     31
300     31
        ..
4440     1
2748     1
2403     1
3546     1
3538     1
2975     1
2427     1
3530     1
2435     1
2443     1
3586     1
4400     1
4751     1
3071     1
3618     1
5204     1
5164     1
4320     1
3610     1
4328     1
3103     1
3594     1
5641     1
5132     1
2307     1
4360     1
5124     1
2323     1
4384     1
2827     1
Name: Horizontal_Distance_To_Roadways, dtype: int64

In [43]:
c =train.Horizontal_Distance_To_Roadways.unique()
print c.size


3250


In [85]:
def roadways_tr(row):
    if row['Horizontal_Distance_To_Roadways'] >= 0 and row['Horizontal_Distance_To_Roadways'] < 500:
        return '0r'
    elif row['Horizontal_Distance_To_Roadways'] >= 500 and row['Horizontal_Distance_To_Roadways'] < 1000:
        return '500r'
    elif row['Horizontal_Distance_To_Roadways'] >= 1000 and row['Horizontal_Distance_To_Roadways'] < 1500:
        return '1000r'
    elif row['Horizontal_Distance_To_Roadways'] >= 1500 and row['Horizontal_Distance_To_Roadways'] < 2000:
        return '1500r'
    elif row['Horizontal_Distance_To_Roadways'] >= 2000 and row['Horizontal_Distance_To_Roadways'] < 2500:
        return '2000r'
    elif row['Horizontal_Distance_To_Roadways'] >= 2500 and row['Horizontal_Distance_To_Roadways'] < 3000:
        return '2500r'
    elif row['Horizontal_Distance_To_Roadways'] >= 3000 and row['Horizontal_Distance_To_Roadways'] < 3500:
        return '3000r'
    elif row['Horizontal_Distance_To_Roadways'] >= 3500 and row['Horizontal_Distance_To_Roadways'] < 4000:
        return '3500r'
    elif row['Horizontal_Distance_To_Roadways'] >= 4000 and row['Horizontal_Distance_To_Roadways'] < 4500:
        return '4000r'
    elif row['Horizontal_Distance_To_Roadways'] >= 4500 and row['Horizontal_Distance_To_Roadways'] < 5000:
        return '4500r'
    elif row['Horizontal_Distance_To_Roadways'] >= 5000 and row['Horizontal_Distance_To_Roadways'] < 5500:
        return '5000r'
    elif row['Horizontal_Distance_To_Roadways'] >= 5500 and row['Horizontal_Distance_To_Roadways'] < 6000:
        return '5500r'
    elif row['Horizontal_Distance_To_Roadways'] >= 6000 and row['Horizontal_Distance_To_Roadways'] < 6500:
        return '6000r'
    elif row['Horizontal_Distance_To_Roadways'] >= 6500 and row['Horizontal_Distance_To_Roadways'] < 7000:
        return '6500r'
    else:
        return 'unknown'
    
train['Horizontal_Distance_To_Roadways'] = train.apply(lambda row: roadways_tr(row), axis=1)
#test['Horizontal_Distance_To_Roadways'] = test.apply(lambda row: roadways_tr(row), axis=1)

In [47]:
train.Slope.value_counts()

11    740
10    739
13    717
14    699
12    677
9     664
15    664
16    640
17    598
8     574
7     573
18    558
20    552
19    519
21    465
6     465
22    458
23    450
5     423
24    394
25    359
26    329
28    313
4     305
27    297
29    258
31    218
30    216
3     210
32    187
33    143
2     134
34    131
35    101
1      78
36     68
37     58
38     36
39     32
41     18
40     16
46     15
0       5
49      5
44      5
42      3
45      3
47      3
43      2
48      1
50      1
52      1
Name: Slope, dtype: int64

In [48]:
train.Vertical_Distance_To_Hydrology.value_counts()

 0      1890
 5       217
 3       206
 4       200
 8       198
 7       182
 10      176
 9       166
 2       165
 6       162
 11      159
 12      159
 13      158
 22      140
 14      140
 1       139
 20      135
 23      133
 16      132
 17      126
 19      126
 21      125
-1       123
 25      122
 18      121
 15      120
-2       120
 37      114
 29      114
 26      114
        ... 
-95        1
-103       1
 249       1
 289       1
 305       1
 321       1
 345       1
 369       1
 393       1
 401       1
-54        1
-110       1
-134       1
 258       1
 266       1
 274       1
 282       1
 330       1
 338       1
 346       1
 554       1
-61        1
-69        1
-85        1
 291       1
 299       1
 315       1
 387       1
 327       1
 395       1
Name: Vertical_Distance_To_Hydrology, dtype: int64

In [49]:
c =train.Vertical_Distance_To_Hydrology.unique()
print c.size

423


In [86]:
def vert_tr(row):
    if row['Vertical_Distance_To_Hydrology'] >= -150 and row['Vertical_Distance_To_Hydrology'] < -100:
        return 'm150'
    elif row['Vertical_Distance_To_Hydrology'] >= -100 and row['Vertical_Distance_To_Hydrology'] < -50:
        return 'm100'
    elif row['Vertical_Distance_To_Hydrology'] >= -50 and row['Vertical_Distance_To_Hydrology'] < 0:
        return 'm50'
    elif row['Vertical_Distance_To_Hydrology'] >= 0 and row['Vertical_Distance_To_Hydrology'] < 50:
        return 'm550'
    elif row['Vertical_Distance_To_Hydrology'] >= 50 and row['Vertical_Distance_To_Hydrology'] < 100:
        return 'm5100'
    elif row['Vertical_Distance_To_Hydrology'] >= 100 and row['Vertical_Distance_To_Hydrology'] < 200:
        return 'm200'
    elif row['Vertical_Distance_To_Hydrology'] >= 200 and row['Vertical_Distance_To_Hydrology'] < 300:
        return 'm300'
    elif row['Vertical_Distance_To_Hydrology'] >= 300 and row['Vertical_Distance_To_Hydrology'] < 400:
        return 'm400'
    elif row['Vertical_Distance_To_Hydrology'] >= 400 and row['Vertical_Distance_To_Hydrology'] < 500:
        return 'm500'
    elif row['Vertical_Distance_To_Hydrology'] >= 500 and row['Vertical_Distance_To_Hydrology'] < 600:
        return 'm600'

    else:
        return 'unknown'
    
train['Vertical_Distance_To_Hydrology'] = train.apply(lambda row: vert_tr(row), axis=1)
#test['Vertical_Distance_To_Hydrology'] = test.apply(lambda row: vert_tr(row), axis=1)

In [57]:
columnsToEncode = list(train.select_dtypes(include=['category','object']))
le = preprocessing.LabelEncoder()
train["Elevation"]=train["Elevation"].astype(str)
train["Horizontal_Distance_To_Hydrology"]=train["Horizontal_Distance_To_Hydrology"].astype(str)
train["Horizontal_Distance_To_Roadways"]=train["Horizontal_Distance_To_Roadways"].astype(str)
train["Vertical_Distance_To_Hydrology"]=train["Vertical_Distance_To_Hydrology"].astype(str)
for feature in columnsToEncode:
    try:
         train[feature] = le.fit_transform(train[feature])
    except:
         print('Error encoding '+feature)

In [58]:
data=train.ix[ :, train.columns != 'Cover_Type']
target1=train['Cover_Type']
train1,test1,train2,test2=train_test_split(data,target1,test_size=0.2,random_state=0)
forest = RandomForestClassifier(n_estimators = 150)
# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(train1,train2)

# Take the same decision trees and run it on the test data
predicted_classification = forest.predict(test1)
print(forest.score(test1,test2))

print(accuracy_score(test2, predicted_classification))

0.830357142857
0.830357142857


In [90]:
train['Soil']=0
for i in range(1,41):
       train['Soil']=train['Soil']+i*train['Soil_Type'+str(i)]
#test['Soil']=0
#for i in range(1,41):
 #      test['Soil']=test['Soil']+i*test['Soil_Type'+str(i)]

In [4]:
train.Soil.value_counts()

10    2142
29    1291
3      962
4      843
23     757
38     728
30     725
32     690
39     657
6      650
2      623
33     616
17     612
13     476
40     459
11     406
1      355
22     345
31     332
24     257
12     227
14     169
5      165
20     139
16     114
35     102
18      60
26      54
19      46
37      34
34      22
21      16
27      15
9       10
36      10
28       9
25       1
8        1
Name: Soil, dtype: int64

In [89]:
train['Wilderness']=0
for i in range(1,4):
       train['Wilderness']=train['Wilderness']+i*train['Wilderness_Area'+str(i)]
#test['Wilderness']=0
#for i in range(1,4):
#       test['Wilderness']=test['Wilderness']+i*test['Wilderness_Area'+str(i)]

In [105]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 13 columns):
Elevation                             15120 non-null object
Aspect                                15120 non-null int64
Slope                                 15120 non-null int64
Horizontal_Distance_To_Hydrology      15120 non-null object
Vertical_Distance_To_Hydrology        15120 non-null object
Horizontal_Distance_To_Roadways       15120 non-null object
Hillshade_9am                         15120 non-null int64
Hillshade_Noon                        15120 non-null int64
Hillshade_3pm                         15120 non-null int64
Horizontal_Distance_To_Fire_Points    15120 non-null int64
Cover_Type                            15120 non-null int64
Wilderness                            15120 non-null int64
Soil                                  15120 non-null int64
dtypes: int64(9), object(4)
memory usage: 1.5+ MB


In [96]:
train = train.drop('Soil_Type1', axis=1)
train = train.drop('Soil_Type2', axis=1)
train = train.drop('Soil_Type3', axis=1)
train = train.drop('Soil_Type4', axis=1)
train = train.drop('Soil_Type5', axis=1)
train = train.drop('Soil_Type6', axis=1)
train = train.drop('Soil_Type7', axis=1)
train = train.drop('Soil_Type8', axis=1)
train = train.drop('Soil_Type9', axis=1)
train = train.drop('Soil_Type10', axis=1)
train = train.drop('Soil_Type11', axis=1)
train = train.drop('Soil_Type12', axis=1)
train = train.drop('Soil_Type13', axis=1)
train = train.drop('Soil_Type14', axis=1)
train = train.drop('Soil_Type15', axis=1)
train = train.drop('Soil_Type16', axis=1)
train = train.drop('Soil_Type17', axis=1)
train = train.drop('Soil_Type18', axis=1)
train = train.drop('Soil_Type19', axis=1)
train = train.drop('Soil_Type20', axis=1)
train = train.drop('Soil_Type21', axis=1)
train = train.drop('Soil_Type22', axis=1)
train = train.drop('Soil_Type23', axis=1)
train = train.drop('Soil_Type24', axis=1)
train = train.drop('Soil_Type25', axis=1)
train = train.drop('Soil_Type26', axis=1)
train = train.drop('Soil_Type27', axis=1)
train = train.drop('Soil_Type28', axis=1)
train = train.drop('Soil_Type29', axis=1)
train = train.drop('Soil_Type30', axis=1)
train = train.drop('Soil_Type31', axis=1)
train = train.drop('Soil_Type32', axis=1)
train = train.drop('Soil_Type33', axis=1)
train = train.drop('Soil_Type34', axis=1)
train = train.drop('Soil_Type35', axis=1)
train = train.drop('Soil_Type36', axis=1)
train = train.drop('Soil_Type37', axis=1)
train = train.drop('Soil_Type38', axis=1)
train = train.drop('Soil_Type39', axis=1)
train = train.drop('Soil_Type40', axis=1)
train = train.drop('Wilderness_Area1', axis=1)
train = train.drop('Wilderness_Area2', axis=1)
train = train.drop('Wilderness_Area3', axis=1)
train = train.drop('Wilderness_Area4', axis=1)


ValueError: labels ['Soil_Type1'] not contained in axis

In [97]:
columnsToEncode = list(train.select_dtypes(include=['category','object']))
le = preprocessing.LabelEncoder()
train["Elevation"]=train["Elevation"].astype(str)
train["Horizontal_Distance_To_Hydrology"]=train["Horizontal_Distance_To_Hydrology"].astype(str)
train["Horizontal_Distance_To_Roadways"]=train["Horizontal_Distance_To_Roadways"].astype(str)
train["Vertical_Distance_To_Hydrology"]=train["Vertical_Distance_To_Hydrology"].astype(str)
for feature in columnsToEncode:
    try:
         train[feature] = le.fit_transform(train[feature])
    except:
         print('Error encoding '+feature)

In [104]:
data=train.ix[ :, train.columns != 'Cover_Type']
target1=train['Cover_Type']
train1,test1,train2,test2=train_test_split(data,target1,test_size=0.2,random_state=0)
forest = RandomForestClassifier(n_estimators = 500)
# Fit the training data to the labels and create the decision trees
forest = forest.fit(train1,train2)

# Take the model and run it on the test data
predicted_classification = forest.predict(test1)
print(accuracy_score(test2, predicted_classification))

0.831018518519


In [103]:
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(train1.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))


Feature ranking:
1. feature 0 (0.229653)
2. feature 11 (0.174271)
3. feature 9 (0.099832)
4. feature 6 (0.072142)
5. feature 10 (0.067507)
6. feature 1 (0.065882)
7. feature 5 (0.060221)
8. feature 8 (0.059784)
9. feature 7 (0.058309)
10. feature 2 (0.046941)
11. feature 3 (0.044574)
12. feature 4 (0.020883)


In [98]:
train.to_csv('trainBD2.csv')
test.to_csv('testBD2.csv')

In [99]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test2, predicted_classification))

[[334  64   1   0   8   2  30]
 [ 77 271  13   0  35  10   5]
 [  0   0 325  35   2  56   0]
 [  0   0   9 417   0  12   0]
 [  1  18   6   0 398   5   0]
 [  0   4  63  17  10 377   0]
 [ 23   2   0   0   0   0 394]]


In [101]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(train1, train2).predict(test1)
print(accuracy_score(test2,y_pred))

0.622023809524


In [106]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565892 entries, 0 to 565891
Data columns (total 57 columns):
Id                                    565892 non-null int64
Elevation                             565892 non-null object
Aspect                                565892 non-null int64
Slope                                 565892 non-null int64
Horizontal_Distance_To_Hydrology      565892 non-null object
Vertical_Distance_To_Hydrology        565892 non-null object
Horizontal_Distance_To_Roadways       565892 non-null object
Hillshade_9am                         565892 non-null int64
Hillshade_Noon                        565892 non-null int64
Hillshade_3pm                         565892 non-null int64
Horizontal_Distance_To_Fire_Points    565892 non-null int64
Wilderness_Area1                      565892 non-null int64
Wilderness_Area2                      565892 non-null int64
Wilderness_Area3                      565892 non-null int64
Wilderness_Area4                      565892 

In [107]:
test.to_csv('dd.csv')

In [108]:
test = pd.read_csv(r'C:\Users\Krishna Teja\Desktop\bigdata\dd.csv')

In [109]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565892 entries, 0 to 565891
Data columns (total 12 columns):
Elevation                             565892 non-null object
Aspect                                565892 non-null int64
Slope                                 565892 non-null int64
Horizontal_Distance_To_Hydrology      565892 non-null object
Vertical_Distance_To_Hydrology        565892 non-null object
Horizontal_Distance_To_Roadways       565892 non-null object
Hillshade_9am                         565892 non-null int64
Hillshade_Noon                        565892 non-null int64
Hillshade_3pm                         565892 non-null int64
Horizontal_Distance_To_Fire_Points    565892 non-null int64
Soil                                  565892 non-null int64
Wilderness                            565892 non-null int64
dtypes: int64(8), object(4)
memory usage: 51.8+ MB


In [110]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 13 columns):
Elevation                             15120 non-null object
Aspect                                15120 non-null int64
Slope                                 15120 non-null int64
Horizontal_Distance_To_Hydrology      15120 non-null object
Vertical_Distance_To_Hydrology        15120 non-null object
Horizontal_Distance_To_Roadways       15120 non-null object
Hillshade_9am                         15120 non-null int64
Hillshade_Noon                        15120 non-null int64
Hillshade_3pm                         15120 non-null int64
Horizontal_Distance_To_Fire_Points    15120 non-null int64
Cover_Type                            15120 non-null int64
Wilderness                            15120 non-null int64
Soil                                  15120 non-null int64
dtypes: int64(9), object(4)
memory usage: 1.5+ MB


In [ ]:
columnsToEncode = list(train.select_dtypes(include=['category','object']))
le = preprocessing.LabelEncoder()
train["Elevation"]=train["Elevation"].astype(str)
train["Horizontal_Distance_To_Hydrology"]=train["Horizontal_Distance_To_Hydrology"].astype(str)
train["Horizontal_Distance_To_Roadways"]=train["Horizontal_Distance_To_Roadways"].astype(str)
train["Vertical_Distance_To_Hydrology"]=train["Vertical_Distance_To_Hydrology"].astype(str)
for feature in columnsToEncode:
    try:
         train[feature] = le.fit_transform(train[feature])
    except:
         print('Error encoding '+feature)
            
columnsToEncode = list(test.select_dtypes(include=['category','object']))
le = preprocessing.LabelEncoder()
test["Elevation"]=test["Elevation"].astype(str)
test["Horizontal_Distance_To_Hydrology"]=test["Horizontal_Distance_To_Hydrology"].astype(str)
test["Horizontal_Distance_To_Roadways"]=test["Horizontal_Distance_To_Roadways"].astype(str)
test["Vertical_Distance_To_Hydrology"]=test["Vertical_Distance_To_Hydrology"].astype(str)
for feature in columnsToEncode:
    try:
         test[feature] = le.fit_transform(test[feature])
    except:
         print('Error encoding '+feature)




data=train.ix[ :, train.columns != 'Cover_Type']
target1=train['Cover_Type']

forest = RandomForestClassifier(n_estimators = 500)
# Fit the training data to the labels and create the decision trees
forest = forest.fit(data,target1)

# Take the model and run it on the test data
predicted_classification = forest.predict(test).astype(int)
predicted_classification.to_csv('pred3.csv')

In [125]:
print predicted_classification

[7 7 7 ..., 1 1 1]


In [126]:
np.savetxt("predictd7d.csv", predicted_classification.astype(int), delimiter=",")

In [127]:
test.to_csv('testingfinalbd.csv')